services:
  daisy:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./data.db:/app/data.db
      - ./static:/app/static
      - ./templates:/app/templates
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:latest
    container_name: daisy-redis
    restart: always

  mysql:
    image: mysql:latest
    container_name: daisy-sql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      retries: 10
      start_period: 10s

volumes:
  mysql_data: